[package]
name = "rust-rng"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.82"
wasm-bindgen-test = "0.3.32"
rand = { version = "0.8.5" }
console_error_panic_hook = "0.1.7"
